In [1]:
import numpy as np
import tensorflow as tf
from keras.engine import Layer
import numpy as np

Using TensorFlow backend.


In [2]:
tf.executing_eagerly()

True

# TF fastfood transform

In [120]:
dd = 4
DD = 32
x = np.array([ 1.6817038, 0.94111705, -0.4930046, 0.9057069 ])

In [136]:
x_in = tf.cast(tf.convert_to_tensor(x), "float32")
print(x_in)
print(x_in.shape)

tf.Tensor([ 1.6817038   0.94111705 -0.4930046   0.9057069 ], shape=(4,), dtype=float32)
(4,)


In [137]:
ll = int(np.ceil(np.log(DD) / np.log(2)))
print(ll)
LL = 2 ** ll
print(LL)

5
32


In [138]:
BB = tf.dtypes.cast(tf.random.uniform((LL,), 0, 2), "int32") * 2 - 1
BB = tf.dtypes.cast(BB, "float32")

In [139]:
print(BB)
print(BB.shape)

tf.Tensor(
[-1.  1. -1.  1. -1. -1.  1.  1.  1.  1.  1. -1. -1.  1. -1.  1.  1.  1.
 -1.  1.  1. -1. -1. -1.  1. -1.  1. -1. -1. -1. -1. -1.], shape=(32,), dtype=float32)
(32,)


In [140]:
Pi =  tf.dtypes.cast(tf.random.shuffle(tf.range(LL)), "float32")

In [141]:
print(Pi)
print(Pi.shape)

tf.Tensor(
[17. 22.  3.  9. 27. 30.  8. 18.  6.  4. 15. 14. 13. 12. 23. 29.  0.  2.
 19.  1. 10. 24. 20. 26. 11. 21. 31.  7.  5. 28. 16. 25.], shape=(32,), dtype=float32)
(32,)


In [142]:
GG = tf.random.normal((LL,))
print(GG)
print(GG.shape)

tf.Tensor(
[-0.40537232 -1.244427    0.2987391  -0.26981288 -0.52363783  0.6045592
 -1.0358177  -0.08275922 -0.5311175  -0.07093018 -1.7000825   0.2783971
 -0.08936618  0.5425918   1.7723031  -0.804397    0.02977141 -0.10901482
  1.3527436   0.83316445 -0.83823496  1.3441519   0.23904982 -0.9521225
 -0.0266678  -1.2736138   0.8829005  -0.39783862  1.25307    -2.3675294
  1.2611406   0.14129047], shape=(32,), dtype=float32)
(32,)


In [143]:
divisor = tf.sqrt(LL * tf.reduce_sum(tf.pow(GG, 2)))
print(divisor)
print(divisor.shape)

tf.Tensor(30.091146, shape=(), dtype=float32)
()


In [144]:
fastfood_vars = [BB, Pi, GG, divisor]

In [145]:
dd_pad = tf.pad(x_in, [[0, LL - dd]])
print(dd_pad)
print(dd_pad.shape)

tf.Tensor(
[ 1.6817038   0.94111705 -0.4930046   0.9057069   0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.        ], shape=(32,), dtype=float32)
(32,)


In [146]:
mul_1 = tf.multiply(BB, dd_pad)
print(mul_1)
print(mul_1.shape)

tf.Tensor(
[-1.6817038   0.94111705  0.4930046   0.9057069  -0.         -0.
  0.          0.          0.          0.          0.         -0.
 -0.          0.         -0.          0.          0.          0.
 -0.          0.          0.         -0.         -0.         -0.
  0.         -0.          0.         -0.         -0.         -0.
 -0.         -0.        ], shape=(32,), dtype=float32)
(32,)


In [147]:
ret = tf.divide(tf.slice(mul_1, [0], [DD]), divisor * np.sqrt(float(DD) / LL))

In [149]:
ret

<tf.Tensor: shape=(32,), dtype=float32, numpy=
array([-0.055887  ,  0.03127555,  0.01638371,  0.03009878, -0.        ,
       -0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        , -0.        ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.        , -0.        , -0.        ,  0.        ,
       -0.        ,  0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        ], dtype=float32)>